CREATE TABLE ASSETS (
  ASSET_ID SERIAL PRIMARY KEY,              
  ASSET_NAME VARCHAR(255) NOT NULL,          
  ASSET_TYPE VARCHAR(100) NOT NULL,         
  CATEGORY VARCHAR(50),                     
  DESCRIPTION TEXT                           
);

CREATE TABLE RISK (
  RISK_RATING_ID SERIAL PRIMARY KEY,         
  RISK_LEVEL INT CHECK (RISK_LEVEL BETWEEN 1 AND 10), 
  LIKELIHOOD DECIMAL(3,1) NOT NULL,          
  IMPACT DECIMAL(3,1) NOT NULL,             
  RISK_SCORE DECIMAL(3,1) GENERATED ALWAYS AS (LIKELIHOOD * IMPACT) STORED 
);

CREATE TABLE THREATS (
  THREATS_ID SERIAL PRIMARY KEY,
  ASSET_ID INT REFERENCES ASSETS(ASSET_ID),  
  RISK_RATING_ID INT REFERENCES RISK(RISK_RATING_ID),
  THREAT_NAME VARCHAR(255) NOT NULL,         
  THREAT_TYPE VARCHAR(100) NOT NULL           
);


CREATE TABLE VULNERABILITIES (
  VULNERABILITY_ID SERIAL PRIMARY KEY,       
  ASSET_ID INT REFERENCES ASSETS(ASSET_ID),  
  RISK_RATING_ID INT REFERENCES RISK(RISK_RATING_ID), 
  VULNERABILITY_NAME VARCHAR(255) NOT NULL,   
  VULNERABILITY_TYPE VARCHAR(100) NOT NULL    
);
